#:schema node_modules/wrangler/config-schema.json
name = "markdown-writer"
main = "src/index.ts"
compatibility_date = "2025-01-09"
compatibility_flags = ["nodejs_compat"]

vars = { AI_MODEL = "@cf/meta/llama-3.3-70b-instruct-fp8-fast" }

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
observability = { enabled = true }

# Bind the Workers AI model catalog. Run machine learning models, powered by serverless GPUs, on Cloudflare’s global network
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#workers-ai
ai = { binding = "AI" }

# Bind a D1 database. D1 is Cloudflare’s native serverless SQL database.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#d1-databases
d1_databases = [
	{ binding = "PAGE_METADATA", database_name = "web-rag-composer-page-metadata", database_id = "9deb74a3-287b-4d8b-a020-6662cfbd9a01", preview_database_id = "56f92781-5084-4333-a331-9cfdfaa0710f" }
]

kv_namespaces = [
	{ binding = "HTML_PREPROCESS", id = "25972a8b0d584077915809ff56a1cfdb", preview_id = "5ddde3eeac90486eab448aa679dca356" }
]

# Bind an R2 Bucket. Use R2 to store arbitrarily large blobs of data, such as files.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#r2-buckets
r2_buckets = [
	{ binding = "RAW_HTML_BUCKET", bucket_name = "web-rag-composer-raw-html", preview_bucket_name = "web-rag-composer-raw-html-dev" },
	{ binding = "KNOWLEDGE_BUCKET", bucket_name = "web-rag-composer-knowledge", preview_bucket_name = "web-rag-composer-knowledge-dev" }
]

# Bind a Vectorize index. Use to store and query vector embeddings for semantic search, classification and other vector search use-cases.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#vectorize-indexes
# vectorize = [
# 	{ binding = "KNOWLEDGE_INDEX", index_name = "web-rag-composer-knowledge-index" },
# 	{ binding = "KNOWLEDGE_INDEX_PREVIEW", index_name = "web-rag-composer-knowledge-index-dev" }
# ]

